### ISSUE TITLE
notes

### ISSUE THREAD

**Issue by Puckoland** [baluchan/sudoku-github#2]
- [x] the `else` [here](https://github.com/baluchan/sudoku-github/blob/main/src/index.ts#L18) is useless since you have return in `if` , you can remove it and save one indentation.
- [x] `storeInput` could preferably return the string (or better yet, return the parsed array right away (`return inputValues.split("", 81).map(Number);`)) => you can get rid of global variable `inputValues` and use it like `const inputValues = storeInput();`, also you should then rename the function to `getInput` for example
- [ ] `counter2` [here](https://github.com/baluchan/sudoku-github/blob/main/src/index.ts#L22) is also useless, you can just use counter1 + 9 in `for` cycle
- [x] variable names (this are just my recommendations): `arr2` -> `sudoku`; `rowArr` -> `row`
- [ ] think about dividing the code into files and then just import the functions to the main `index.ts` (btw, you can also encapsulate these functions into classes)

**Comment by baluchan** [comment]
done
